FROM golang:latest
ARG TARGETOS
ARG TARGETARCH

WORKDIR /app
COPY pkg ./pkg
COPY frontend ./frontend
COPY go.mod ./
RUN go mod tidy -e

RUN cd pkg && CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -o goclient

CMD ["/app/pkg/goclient"]
