apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-pv-claim
  labels:
    type: local
    app: server
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pv-claim
  labels:
    app: server
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi