apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
    - port: 80
  selector:
    app: server
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pv-claim
  labels:
    app: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server
        tier: frontend
    spec:
      containers:
      - image: higgins113/my-go-server
        name: server
        env:
        - name: DB_HOST
          value: server-mysql
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: server
        volumeMounts:
        - name: server-persistent-storage
          mountPath: /var/www/html
      - image: higgins113/my-go-client
        name: client
      volumes:
      - name: server-persistent-storage
        persistentVolumeClaim:
          claimName: server-pv-claim
