FROM golang:latest
ARG TARGETOS
ARG TARGETARCH

WORKDIR /app
COPY pkg ./pkg
COPY init ./init
COPY go.mod ./
COPY createDB.sql ./
RUN go mod tidy -e

RUN cd init && CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -o goserver

CMD ["/app/init/goserver"]
